### ISSUE TITLE
getShippingMethod causes ErrorException

### ISSUE THREAD

**Issue by RitterKnightCreative** [FosterCommerce/shipstation-connect#2]
Client tried pulling an order today.

This appeared in SS:

``An error occurred attempting to update orders: Invalid XML. Error: 'Data at the root level is invalid. Line 1, position 1.' We received: '{"error":"ErrorException"}'
``

**Comment by RitterKnightCreative** [comment]
Did some more debugging, client is offering free shipping on some orders and I think this method is breaking it. Commented out line 97 and 101, immediately brought in the order.

```
   public function shippingMethod(\SimpleXMLElement $order_xml, $order) {
        $shippingMethod = null;
      //  if (!is_null($shippingMethod) || ($shippingMethod = $order->getShippingMethod()->handle)) {
            $this->addChildWithCDATA($order_xml, 'ShippingMethod', $shippingMethod);
        //}
    }

**Comment by sjcallender** [comment]
More info. The shipping method in Craft is blank, which is odd, but it happened and needs to be accounted for or given a better error message.

![image](https://user-images.githubusercontent.com/984311/45858493-c586f680-bd2b-11e8-807d-1875ffcb50c2.png)

**Comment by RitterKnightCreative** [comment]
Reopening. 

Had an order come in last night with no shipping method attached, trying to get to the bottom of it, but the plugin shouldn't error out regardless.

**Comment by sjcallender** [comment]
Hey David. What's that SS complaint look like? Any specific errors you can throw our way?

**Comment by RitterKnightCreative** [comment]
Sorry... you bet, here's the trace from the log:
```
2018-10-22 08:58:21 [-][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Trying to get property of non-object in /home/client/site/vendor/fostercommerce/shipstationconnect/src/services/Xml.php:122
#1 /home/client/site/vendor/fostercommerce/shipstationconnect/src/services/Xml.php(122): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/home/client/site...', 122, Array)
#2 /home/client/site/vendor/fostercommerce/shipstationconnect/src/services/Xml.php(90): fostercommerce\shipstationconnect\services\Xml->shippingMethod(Object(SimpleXMLElement), Object(craft\commerce\elements\Order))
#3 /home/client/site/vendor/fostercommerce/shipstationconnect/src/services/Xml.php(32): fostercommerce\shipstationconnect\services\Xml->order(Object(SimpleXMLElement), Object(craft\commerce\elements\Order))
#4 /home/client/site/vendor/fostercommerce/shipstationconnect/src/controllers/OrdersController.php(113): fostercommerce\shipstationconnect\services\Xml->orders(Object(SimpleXMLElement), Array)
#5 /home/client/site/vendor/fostercommerce/shipstationconnect/src/controllers/OrdersController.php(39): fostercommerce\shipstationconnect\controllers\OrdersController->getOrders()
#6 [internal function]: fostercommerce\shipstationconnect\controllers\OrdersController->actionProcess()
```
